In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("priyankraval/nurse-stress-prediction-wearable-sensors")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/priyankraval/nurse-stress-prediction-wearable-sensors?dataset_version_number=1...

100%|██████████| 76.2M/76.2M [00:00<00:00, 125MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/priyankraval/nurse-stress-prediction-wearable-sensors/versions/1

In [5]:
import pandas as pd
import os

df = pd.read_csv(os.path.join(path, "merged_data.csv"))
df.head()

/tmp/ipython-input-197/562419876.py:4: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(path, "merged_data.csv"))

,X,Y,Z,EDA,HR,TEMP,id,datetime,label
0,-13.0,-61.0,5.0,6.769995,99.43,31.17,15,2020-07-08 14:03:00.000000000,2.0
1,-20.0,-69.0,-3.0,6.769995,99.43,31.17,15,2020-07-08 14:03:00.031249920,2.0
2,-31.0,-78.0,-15.0,6.769995,99.43,31.17,15,2020-07-08 14:03:00.062500096,2.0
3,-47.0,-65.0,-38.0,6.769995,99.43,31.17,15,2020-07-08 14:03:00.093750016,2.0
4,-67.0,-57.0,-53.0,6.769995,99.43,31.17,15,2020-07-08 14:03:00.124999936,2.0

In [7]:
df['label'].unique()
df['label'].value_counts()

label
2.0    8540583
0.0    2162246
1.0     806222
Name: count, dtype: int64

In [10]:
label_counts = df['label'].value_counts()
ratio = label_counts[2.0] / label_counts[0.0]
print(f"Ratio of label 2.0 to label 0.0 counts: {ratio}")

Ratio of label 2.0 to label 0.0 counts: 3.9498664814271827

In [11]:
df.groupby('label')[['HR','EDA','TEMP']].mean()

              HR       EDA       TEMP
label
0.0    86.615423  2.950669  31.638143
1.0    86.452402  3.068973  31.987733
2.0    85.479283  3.682631  32.408568